[package]
name = "wally-vendor"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Vendor and verify Wally dependencies for .rbxm releases"
repository = "https://github.com/SequesteredOne/wally-vendor"
readme = "README.md"

[dependencies]
clap = "4.5.45"
serde = "1.0.219"
